// This file was auto-generated by ML.NET Model Builder.
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace AnalyseApp
{
    public partial class Bundesliga
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"AwayTeamGoals", @"AwayTeamGoals"),new InputOutputColumnPair(@"HomeTeamShots", @"HomeTeamShots"),new InputOutputColumnPair(@"AwayTeamShots", @"AwayTeamShots"),new InputOutputColumnPair(@"HomeTeamHalfTimeGoals", @"HomeTeamHalfTimeGoals"),new InputOutputColumnPair(@"AwayTeamHalfTimeGoals", @"AwayTeamHalfTimeGoals"),new InputOutputColumnPair(@"HomeTeamFullTimeGoals", @"HomeTeamFullTimeGoals"),new InputOutputColumnPair(@"AwayTeamFullTimeGoals", @"AwayTeamFullTimeGoals"),new InputOutputColumnPair(@"PredictedLabel", @"PredictedLabel")})      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"HomeTeam",outputColumnName:@"HomeTeam"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"AwayTeam",outputColumnName:@"AwayTeam"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"AwayTeamGoals",@"HomeTeamShots",@"AwayTeamShots",@"HomeTeamHalfTimeGoals",@"AwayTeamHalfTimeGoals",@"HomeTeamFullTimeGoals",@"AwayTeamFullTimeGoals",@"PredictedLabel",@"HomeTeam",@"AwayTeam"}))      
                                    .Append(mlContext.Regression.Trainers.FastTree(new FastTreeRegressionTrainer.Options(){NumberOfLeaves=4,MinimumExampleCountPerLeaf=2,NumberOfTrees=4,MaximumBinCountPerFeature=674,FeatureFraction=0.99999999,LearningRate=0.677485713932099,LabelColumnName=@"HomeTeamGoals",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
